#!/bin/bash

# Initialize variables
EXTRA_ARGS=""

# Check for arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -fc|-fl)
            EXTRA_ARGS="$EXTRA_ARGS $1 $2"
            shift 2
            ;;
        -p)
            EXTRA_ARGS="$EXTRA_ARGS $1 $2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Run httpx without default ports unless -p is provided
httpx -title -sc -server -fr -td -ip -cl $EXTRA_ARGS
